name: Test released version

on: [push]

jobs:
  test_released_job:
    runs-on: ubuntu-latest
    name: A job to test the latest released ncu-action
    steps:
    - uses: actions/checkout@v2
    - name: Test the released step
      id: test_released
      uses: fzwael/ncu-action@v1.3.0
      with:
        ncu-options: ""
